### PR TITLE
executing standalone mpi from java and mpi workers with a script

### PR DESCRIPTION
**Pull request by ahmet-uyar**
Hi Supun,

I executed mpirun directly from java and used mpiworker.sh script to start workers. You can use the debugging feature now. 
I also sent command line parameters from mpimaster to workers as environment variables. So, mpiworker.sh script is much more readable. 
If you can test the debugging first, that would be great. 

Ahmet

### CODE REVIEW

**Comment by supunkamburugamuve** [comment]
@ahmet-uyar I was trying to understand how the two scripts are connected. I can see they both invoke java. I thought one script is going to use the other in the mpi command

**Comment by ahmet-uyar** [comment]
@supunkamburugamuve, both standalone and slurm use a single script. 
In standalone, the script is used as the prelaunch script when starting workers.
In Slurm, the script is used in the submitting client to invoke sbatch command to submit the mpi job.

**Comment by supunkamburugamuve** [comment]
I could find one mpi launcher script. Is there a one in standalone directory?

**Comment by ahmet-uyar** [comment]
@supunkamburugamuve There is mpiworker.sh script in standalone directory.

**Comment by supunkamburugamuve** [comment]
I see you have included the mpi command launch in the Java program. How can we specify custom MPI command arguments?

**Comment by ahmet-uyar** [comment]
[I see you have included the mpi command launch in the Java program. How can we specify custom MPI command arguments?]

@supunkamburugamuve, we can either add a configuration parameter for that or have two separate scripts.  One for the mpimaster and the other is for the mpiworker.

**Comment by supunkamburugamuve** [comment]
I'm fine with both options.

**Comment by supunkamburugamuve** [comment]
@chathurawidanage wdyt about these options?

**Comment by chathurawidanage** [comment]
+1 for adding a config parameter. Are we going to add that to YAML files or accept from the twister2 submit command itself?

**Comment by ahmet-uyar** [comment]
@chathurawidanage   I think YAML file would be better.

**Pull request merged**
