### PR TITLE
Tset Windowing Implementation [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by vibhatha**

### CODE REVIEW

**Comment by supunkamburugamuve** [comment]
Lets add documentation for Windowing TSet API

**Comment by vibhatha** [comment]
> Let's add documentation for Windowing TSet API

Yes, let's do it.

**Comment by supunkamburugamuve** [comment]
Please remove the Pytorch related stuff as well.

**Comment by nirandaperera** [comment]
My personal opinion is, we need to take off the `link.countWindow(len, computeFn)` and make is something like, `link.countWindow(len).process(computeFn)`. 
ATM we have both the options and it would be confusing for the user IMO. (we may put the identity function as the default compute)

**Pull request merged**
